### PR TITLE
Support for whitelist.json instead of whiteListedNames

### PR DESCRIPTION
**Pull request by spanasiuk**
Implementation of what's being requested under issue https://github.com/vincss/mcsleepingserverstarter/issues/202.
If `useWhitelistFile` is set to `true`, `whiteListedNames` is ignored, and `whitelist.json` file is used instead.
With this change, I've added support for UUID check to fully utilize `whitelist.json` contents and provide additional security. 
The issue I've noticed is that there's no whitelist checks for Bedrock users at the moment, but it's out of the scope of the current PR

### CODE REVIEW

**Comment by spanasiuk** [comment]
Implementation of what's being requested under issue https://github.com/vincss/mcsleepingserverstarter/issues/202

**Comment by vincss** [comment]
Thanks for the PR ! 
"no whitelist checks for Bedrock users at the moment" => Bedrock is not working for the moment anyway.

**Comment by spanasiuk** [comment]
Btw, it might also make sense to add some flag that will switch to using `server.properties` for settings like `serverPort`, `serverOnlineMode`, `maxPlayers`, `useWhitelistFile`. I can do that after the review process for this PR

**Comment by vincss** [comment]
Seems good to me :-) 
A little message in the change log and increase the version in the package.json and it's good to be merged.
Thanks.

**Review by vincss — APPROVED** [review]

**Review by vincss — APPROVED** [review]

**Pull request merged**
