### PR TITLE
add pterodactyl egg

### PR DESCRIPTION
**Pull request by BoredKevin**
Add a pterodactyl egg for mcsleepingserverstarter

Let me know if you have any problems with it

### CODE REVIEW

**Review by iwa — APPROVED** [review]
no issue for me, @vincss wbu?

**Comment by BoredKevin** [comment]
Hello, forgot to mention that when merging, please add credit to the original [repository](https://github.com/BoredKevin/mcsleepingserverstarter-ptero-egg).

Thanks.

**Comment by BoredKevin** [comment]
added some fixes to the config file, now it should return the server jarfile variable to the startup command

**Comment by vincss** [comment]
Hi ! 
Thanks for your contribution !
Maybe put it on the docs folder ? 
https://github.com/vincss/mcsleepingserverstarter/tree/master/docs

**Comment by vincss** [comment]
Thanks for the change.
Maybe add an entry in the readme : 
https://github.com/vincss/mcsleepingserverstarter#-pufferpanel
But for me it's ok.

**Comment by BoredKevin** [comment]
^ tell me if this looks good or not

**Pull request merged**
